title = "Elvish: Friendly and Expressive Shell"
author = "Qi Xiao"
feedPosts = 10
template = "template.html"
rootURL = "https://elv.sh"

[index]
name = "home"
title = "home"

[[categories]]
name = "download"
title = "get"

[[categories]]
name = "learn"
title = "learn"

[[categories]]
name = "ref"
title = "ref"

[[categories]]
name = "blog"
title = "blog"
