title = "Elvish: Friendly and Expressive Shell"
author = "Qi Xiao"
feedPosts = 10
template = "template.html"
rootURL = "https://elv.sh"

[index]
name = "home"

[[categories]]
name = "get"
title = "Get Elvish"

[[categories]]
name = "learn"
title = "Learn Elvish"

[[categories]]
name = "ref"
title = "Elvish Reference"

[[categories]]
name = "blog"
title = "Elvish Blog"
