platform: x64
branches:
  only:
    - master
clone_folder: c:\gopath\src\github.com\elves\elvish
environment:
  GOPATH: c:\gopath
install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%;C:\msys64\usr\bin
  - go version
  - go env
  - choco install codecov
build_script:
  - make appveyor