language: go
os:
  - linux
  - osx
sudo: false
go:
  - "1.11"
  - "1.10"
env: CGO_ENABLED=0
jobs:
  include:
    - stage: coverage
      script: make upload-codecov-travis upload-coveralls-travis
      # Not enabled for pull requests yet
      if: type = push
script: make test
