language: go
os:
  - linux
  - osx
sudo: false
go:
  - "1.11"
  - "1.10"
env: CGO_ENABLED=0
jobs:
  include:
    # NOTE: Coverages are not enabled for pull requests yet
    - stage: coverage
      script: make coverage-travis
      if: type = push
      os: linux
    - stage: coverage
      script: make coverage-travis
      if: type = push
      os: osx
script: make test
