language: go
os:
  - linux
  - osx
sudo: false
go:
  - "1.11"
  - "1.10"
env: CGO_ENABLED=0
jobs:
  include:
    # NOTE: Coverages are not enabled for pull requests yet
    - stage: deploy
      name: Upload Linux coverage profiles
      script: make coverage-travis
      if: type = push
      os: linux
    - name: Upload macOS coverage profiles
      script: make coverage-travis
      if: type = push
      os: osx
    - name: Deploy artifacts to bintray
      script: make deploy-travis
      if: type = push
script: make test
