language: go
go:
    - 1.5
sudo: false
os:
    - linux
    - osx
script:
    make travis
deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: elvish
    endpoint: elvish.s3.eu-central-1.amazonaws.com
    region: eu-central-1
