[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "v1.3.1"

[[constraint]]
  name = "github.com/xiaq/persistent"
  branch = "master"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  name = "github.com/kr/pty"
  version = "v1.0.1"
